parameters: {}

stages:
  - stage: CI
    displayName: 'Continuous Integration'
    jobs:
      - job: build_and_test
        displayName: 'Build, Lint, Test'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          matrix:
            Node18:
              NODE_VERSION: '18'
            Node20:
              NODE_VERSION: '20'
        steps:
          - checkout: self
            fetchDepth: 0

          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(Pipeline.Workspace)/.npm
            displayName: 'Cache npm'

          - task: NodeTool@0
            inputs:
              versionSpec: '$(NODE_VERSION)'
            displayName: 'Use Node $(NODE_VERSION)'

          - script: |
              npm ci --no-audit --no-fund
            displayName: 'npm ci'

          - script: |
              npm run lint
            displayName: 'ESLint'

          - script: |
              npm test -- --ci --reporters=default --coverage
            displayName: 'Run tests and collect coverage'
            continueOnError: false

          - task: PublishTestResults@2
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test-results-*.xml'
              failTaskOnFailedTests: true
            condition: always()

          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: 'Cobertura'
              summaryFileLocation: 'coverage/cobertura-coverage.xml'
            condition: always()

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifact: 'source'
            displayName: 'Publish source artifact'