parameters:
  - name: dependsOn
    type: string
  - name: azureSubscription
    type: string
  - name: appName
    type: string
  - name: resourceGroup
    type: string
  - name: environmentName
    type: string

stages:
  - stage: Deploy
    displayName: 'Deploy to Staging'
    dependsOn: ${{ parameters.dependsOn }}
    condition: succeeded()
    jobs:
      - deployment: deploy_to_appservice
        displayName: 'Deploy container to Azure Web App (Linux)'
        environment: ${{ parameters.environmentName }}
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebAppContainer@1
                  displayName: 'Deploy image from ACR to App Service'
                  inputs:
                    azureSubscription: ${{ parameters.azureSubscription }}
                    appName: ${{ parameters.appName }}
                    resourceGroupName: ${{ parameters.resourceGroup }}
                    imageName: '$(containerRegistry)/$(imageName):$(imageTag)'